// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  httpserver

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( uploadDocumentTransport ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* uploadDocumentTransport ) UnmarshalJSON([]byte) error { return nil }
func ( uploadDocumentTransport ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* uploadDocumentTransport ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_uploadDocumentTransport *uploadDocumentTransport

func ( getWarehousesResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* getWarehousesResponse ) UnmarshalJSON([]byte) error { return nil }
func ( getWarehousesResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* getWarehousesResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_getWarehousesResponse *getWarehousesResponse

func ( getWarehousesTransport ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* getWarehousesTransport ) UnmarshalJSON([]byte) error { return nil }
func ( getWarehousesTransport ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* getWarehousesTransport ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_getWarehousesTransport *getWarehousesTransport

func ( getDetailsResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* getDetailsResponse ) UnmarshalJSON([]byte) error { return nil }
func ( getDetailsResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* getDetailsResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_getDetailsResponse *getDetailsResponse

func ( getDetailsTransport ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* getDetailsTransport ) UnmarshalJSON([]byte) error { return nil }
func ( getDetailsTransport ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* getDetailsTransport ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_getDetailsTransport *getDetailsTransport

func ( getDetailsEmbedStructResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* getDetailsEmbedStructResponse ) UnmarshalJSON([]byte) error { return nil }
func ( getDetailsEmbedStructResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* getDetailsEmbedStructResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_getDetailsEmbedStructResponse *getDetailsEmbedStructResponse

func ( getDetailsEmbedStructTransport ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* getDetailsEmbedStructTransport ) UnmarshalJSON([]byte) error { return nil }
func ( getDetailsEmbedStructTransport ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* getDetailsEmbedStructTransport ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_getDetailsEmbedStructTransport *getDetailsEmbedStructTransport

func ( getDetailsListEmbedStructResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* getDetailsListEmbedStructResponse ) UnmarshalJSON([]byte) error { return nil }
func ( getDetailsListEmbedStructResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* getDetailsListEmbedStructResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_getDetailsListEmbedStructResponse *getDetailsListEmbedStructResponse

func ( getDetailsListEmbedStructTransport ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* getDetailsListEmbedStructTransport ) UnmarshalJSON([]byte) error { return nil }
func ( getDetailsListEmbedStructTransport ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* getDetailsListEmbedStructTransport ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_getDetailsListEmbedStructTransport *getDetailsListEmbedStructTransport

func ( putDetailsRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* putDetailsRequest ) UnmarshalJSON([]byte) error { return nil }
func ( putDetailsRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* putDetailsRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_putDetailsRequest *putDetailsRequest

func ( putDetailsResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* putDetailsResponse ) UnmarshalJSON([]byte) error { return nil }
func ( putDetailsResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* putDetailsResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_putDetailsResponse *putDetailsResponse

func ( putDetailsTransport ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* putDetailsTransport ) UnmarshalJSON([]byte) error { return nil }
func ( putDetailsTransport ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* putDetailsTransport ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_putDetailsTransport *putDetailsTransport

func ( getSomeElseDataUtf8Response ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* getSomeElseDataUtf8Response ) UnmarshalJSON([]byte) error { return nil }
func ( getSomeElseDataUtf8Response ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* getSomeElseDataUtf8Response ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_getSomeElseDataUtf8Response *getSomeElseDataUtf8Response

func ( getSomeElseDataUtf8Transport ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* getSomeElseDataUtf8Transport ) UnmarshalJSON([]byte) error { return nil }
func ( getSomeElseDataUtf8Transport ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* getSomeElseDataUtf8Transport ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_getSomeElseDataUtf8Transport *getSomeElseDataUtf8Transport

func ( getFileTransport ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* getFileTransport ) UnmarshalJSON([]byte) error { return nil }
func ( getFileTransport ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* getFileTransport ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_getFileTransport *getFileTransport
