// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package httpserver

import (
	json "encoding/json"
	_v1 "github.com/wildberries-ru/go-transport-generator/example/api/v1"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver(in *jlexer.Lexer, out *putDetailsTransport) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver(out *jwriter.Writer, in putDetailsTransport) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v putDetailsTransport) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v putDetailsTransport) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *putDetailsTransport) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *putDetailsTransport) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver(l, v)
}
func easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver1(in *jlexer.Lexer, out *putDetailsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Cool":
			easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV1(in, &out.Cool)
		case "Nothing":
			easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV11(in, &out.Nothing)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver1(out *jwriter.Writer, in putDetailsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Cool\":"
		out.RawString(prefix[1:])
		easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV1(out, in.Cool)
	}
	{
		const prefix string = ",\"Nothing\":"
		out.RawString(prefix)
		easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV11(out, in.Nothing)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v putDetailsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v putDetailsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *putDetailsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *putDetailsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver1(l, v)
}
func easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV11(in *jlexer.Lexer, out *_v1.Namespace) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV11(out *jwriter.Writer, in _v1.Namespace) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	out.RawByte('}')
}
func easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV1(in *jlexer.Lexer, out *_v1.Detail) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "namespace":
			out.Namespace = string(in.String())
		case "name":
			out.Name = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV1(out *jwriter.Writer, in _v1.Detail) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"namespace\":"
		out.RawString(prefix[1:])
		out.String(string(in.Namespace))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	out.RawByte('}')
}
func easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver2(in *jlexer.Lexer, out *putDetailsRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ThePretty":
			easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV1(in, &out.Pretty)
		case "Yang":
			easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV11(in, &out.Yang)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver2(out *jwriter.Writer, in putDetailsRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ThePretty\":"
		out.RawString(prefix[1:])
		easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV1(out, in.Pretty)
	}
	{
		const prefix string = ",\"Yang\":"
		out.RawString(prefix)
		easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV11(out, in.Yang)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v putDetailsRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v putDetailsRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *putDetailsRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *putDetailsRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver2(l, v)
}
func easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver3(in *jlexer.Lexer, out *getWarehousesTransport) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver3(out *jwriter.Writer, in getWarehousesTransport) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v getWarehousesTransport) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getWarehousesTransport) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getWarehousesTransport) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getWarehousesTransport) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver3(l, v)
}
func easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver4(in *jlexer.Lexer, out *getWarehousesResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Pets":
			if in.IsNull() {
				in.Skip()
				out.Pets = nil
			} else {
				in.Delim('[')
				if out.Pets == nil {
					if !in.IsDelim(']') {
						out.Pets = make([]_v1.Detail, 0, 2)
					} else {
						out.Pets = []_v1.Detail{}
					}
				} else {
					out.Pets = (out.Pets)[:0]
				}
				for !in.IsDelim(']') {
					var v1 _v1.Detail
					easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV1(in, &v1)
					out.Pets = append(out.Pets, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver4(out *jwriter.Writer, in getWarehousesResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Pets\":"
		out.RawString(prefix[1:])
		if in.Pets == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Pets {
				if v2 > 0 {
					out.RawByte(',')
				}
				easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV1(out, v3)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v getWarehousesResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getWarehousesResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getWarehousesResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getWarehousesResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver4(l, v)
}
func easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver5(in *jlexer.Lexer, out *getSomeElseDataUtf8Transport) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver5(out *jwriter.Writer, in getSomeElseDataUtf8Transport) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v getSomeElseDataUtf8Transport) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getSomeElseDataUtf8Transport) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getSomeElseDataUtf8Transport) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getSomeElseDataUtf8Transport) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver5(l, v)
}
func easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver6(in *jlexer.Lexer, out *getSomeElseDataUtf8Response) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "cool":
			easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV1(in, &out.Cool)
		case "id":
			if in.IsNull() {
				in.Skip()
				out.Id = nil
			} else {
				if out.Id == nil {
					out.Id = new(string)
				}
				*out.Id = string(in.String())
			}
		case "TheNothing":
			easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV11(in, &out.Nothing)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver6(out *jwriter.Writer, in getSomeElseDataUtf8Response) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"cool\":"
		out.RawString(prefix[1:])
		easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV1(out, in.Cool)
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		if in.Id == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Id))
		}
	}
	{
		const prefix string = ",\"TheNothing\":"
		out.RawString(prefix)
		easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV11(out, in.Nothing)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v getSomeElseDataUtf8Response) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getSomeElseDataUtf8Response) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getSomeElseDataUtf8Response) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getSomeElseDataUtf8Response) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver6(l, v)
}
func easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver7(in *jlexer.Lexer, out *getDetailsTransport) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver7(out *jwriter.Writer, in getDetailsTransport) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v getDetailsTransport) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getDetailsTransport) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getDetailsTransport) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getDetailsTransport) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver7(l, v)
}
func easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver8(in *jlexer.Lexer, out *getDetailsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Det":
			easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV1(in, &out.Det)
		case "Ns":
			easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV11(in, &out.Ns)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver8(out *jwriter.Writer, in getDetailsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Det\":"
		out.RawString(prefix[1:])
		easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV1(out, in.Det)
	}
	{
		const prefix string = ",\"Ns\":"
		out.RawString(prefix)
		easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV11(out, in.Ns)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v getDetailsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getDetailsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getDetailsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getDetailsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver8(l, v)
}
func easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver9(in *jlexer.Lexer, out *getDetailsListEmbedStructTransport) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver9(out *jwriter.Writer, in getDetailsListEmbedStructTransport) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v getDetailsListEmbedStructTransport) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getDetailsListEmbedStructTransport) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getDetailsListEmbedStructTransport) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getDetailsListEmbedStructTransport) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver9(l, v)
}
func easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver10(in *jlexer.Lexer, out *getDetailsListEmbedStructResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(getDetailsListEmbedStructResponse, 0, 2)
			} else {
				*out = getDetailsListEmbedStructResponse{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v4 _v1.Detail
			easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV1(in, &v4)
			*out = append(*out, v4)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver10(out *jwriter.Writer, in getDetailsListEmbedStructResponse) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v5, v6 := range in {
			if v5 > 0 {
				out.RawByte(',')
			}
			easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV1(out, v6)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v getDetailsListEmbedStructResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getDetailsListEmbedStructResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getDetailsListEmbedStructResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getDetailsListEmbedStructResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver10(l, v)
}
func easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver11(in *jlexer.Lexer, out *getDetailsEmbedStructTransport) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver11(out *jwriter.Writer, in getDetailsEmbedStructTransport) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v getDetailsEmbedStructTransport) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getDetailsEmbedStructTransport) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getDetailsEmbedStructTransport) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getDetailsEmbedStructTransport) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver11(l, v)
}
func easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver12(in *jlexer.Lexer, out *getDetailsEmbedStructResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "detail":
			easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV1(in, &out.Detail)
		case "namespace":
			easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV11(in, &out.Namespace)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver12(out *jwriter.Writer, in getDetailsEmbedStructResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"detail\":"
		out.RawString(prefix[1:])
		easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV1(out, in.Detail)
	}
	{
		const prefix string = ",\"namespace\":"
		out.RawString(prefix)
		easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV11(out, in.Namespace)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v getDetailsEmbedStructResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getDetailsEmbedStructResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC87d08bdEncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getDetailsEmbedStructResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getDetailsEmbedStructResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC87d08bdDecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleServiceHttpserver12(l, v)
}
