// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package v1

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson55999d76DecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV1(in *jlexer.Lexer, out *CreateMultipartUploadData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "some":
			out.Some = int(in.Int())
		case "upload_id":
			out.UploadID = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson55999d76EncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV1(out *jwriter.Writer, in CreateMultipartUploadData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"some\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Some))
	}
	{
		const prefix string = ",\"upload_id\":"
		out.RawString(prefix)
		out.String(string(in.UploadID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateMultipartUploadData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson55999d76EncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateMultipartUploadData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson55999d76EncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateMultipartUploadData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson55999d76DecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateMultipartUploadData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson55999d76DecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV1(l, v)
}
func easyjson55999d76DecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV11(in *jlexer.Lexer, out *AdditionalErrors) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "lastName":
			out.LastName = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson55999d76EncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV11(out *jwriter.Writer, in AdditionalErrors) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"lastName\":"
		out.RawString(prefix)
		out.String(string(in.LastName))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AdditionalErrors) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson55999d76EncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AdditionalErrors) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson55999d76EncodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AdditionalErrors) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson55999d76DecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AdditionalErrors) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson55999d76DecodeGitWildberriesRuInfrastructureGoTransportGeneratorExampleApiV11(l, v)
}
